### PR TITLE
CI: build docs on 3.7, not 3.9

### LINKED ISSUE #54: Docs build on latest Python (i.e., Python 3.9)
https://github.com/pcdshub/pcds-ci-helpers/blob/506540f9b20dfd272505190f674d9161d00736f1/travis/shared_configs/docs-build.yml#L29

`PYTHON_VERSION` is unset for the docs build, making it default to the latest

https://travis-ci.com/github/pcdshub/pcdsdevices/jobs/401771827

Considering we don't run tests on 3.9 even, I think this can be considered a bug

### PR DESCRIPTION
**Pull request by klauer**
Closes #54

### CODE REVIEW

**Review by hhslepicka — APPROVED** [review]

**Comment by klauer** [comment]
Just removed travis-ci.org webhook; PR build is passing

**Comment by ZLLentz** [comment]
This broke docs builds and anaconda uploads for modules that don't work on 3.7 yet, such as `hutch-python`

**Comment by ZLLentz** [comment]
I do realize that it is very sad that `hutch-python` is stuck on 3.6 so I'm approaching it from that angle

**Comment by klauer** [comment]
OK, will switch to 3.6.

**Pull request merged**
