### PR TITLE
MAINT: pin packaging back for the twincat builds to avoid a removal

### LINKED ISSUE #89: TwinCAT documentation building broken (packaging.version.LegacyVersion)
Ref: https://app.travis-ci.com/github/pcdshub/lcls-twincat-vacuum/jobs/590814009

```
[0K$ ads-deploy docs --output "${DOCS_FOLDER}/source" "${SOLUTION}"
INFO:ads_deploy.docs:Rendering general template: index.rst -> index.rst
INFO:ads_deploy.docs:Rendering per-tsproj template: {{tsproj.name}}_boxes.rst -> L2SIVacuumLib_boxes.rst
INFO:ads_deploy.docs:Rendering per-tsproj template: {{tsproj.name}}_nc.rst -> L2SIVacuumLib_nc.rst
INFO:ads_deploy.docs:Rendering per-PLC template: {{tsproj.name}}_{{plc.name}}_epics.rst -> L2SIVacuumLib_L2SIVacuum_epics.rst
INFO:ads_deploy.docs:Rendering per-tsproj template: {{tsproj.name}}_pragmas.rst -> L2SIVacuumLib_pragmas.rst
INFO:ads_deploy.docs:Rendering per-PLC template: {{tsproj.name}}_{{plc.name}}_summary.rst -> L2SIVacuumLib_L2SIVacuum_summary.rst
INFO:ads_deploy.docs:Rendering per-tsproj template: {{tsproj.name}}_links.rst -> L2SIVacuumLib_links.rst
INFO:ads_deploy.docs:Rendering per-PLC template: {{tsproj.name}}_{{plc.name}}_source.rst -> L2SIVacuumLib_L2SIVacuum_source.rst
INFO:ads_deploy.docs:Done
[0mtravis_time:end:31f120a7:start=1670622672853903537,finish=1670622677592423657,duration=4738520120,event=script
[0K[32;1mThe command "ads-deploy docs --output "${DOCS_FOLDER}/source" "${SOLUTION}"" exited with 0.[0m
travis_time:start:272f9f38
[0K$ set -e
pushd ${DOCS_FOLDER}
make html
popd

~/docs ~/build/pcdshub/lcls-twincat-vacuum
[01mRunning Sphinx v5.3.0[39;49;00m

[91mConfiguration error:[39;49;00m
There is a programmable error in your configuration file:

Traceback (most recent call last):
  File "/home/travis/miniconda/lib/python3.9/site-packages/sphinx/config.py", line 350, in eval_config_file
    exec(code, namespace)
  File "/home/travis/docs/source/conf.py", line 18, in <module>
    import doctr_versions_menu
  File "/home/travis/miniconda/lib/python3.9/site-packages/doctr_versions_menu/__init__.py", line 14, in <module>
    from . import cli, ext
  File "/home/travis/miniconda/lib/python3.9/site-packages/doctr_versions_menu/cli.py", line 15, in <module>
    from .version_data import get_version_data
  File "/home/travis/miniconda/lib/python3.9/site-packages/doctr_versions_menu/version_data.py", line 10, in <module>
    from .groups import get_groups
  File "/home/travis/miniconda/lib/python3.9/site-packages/doctr_versions_menu/groups.py", line 2, in <module>
    from packaging.version import LegacyVersion
ImportError: cannot import name 'LegacyVersion' from 'packaging.version' (/home/travis/miniconda/lib/python3.9/site-packages/packaging/version.py)

Makefile:20: recipe for target 'html' failed
make: *** [html] Error 2
```

### PR DESCRIPTION
**Pull request by ZLLentz**
Closes #89

See https://app.travis-ci.com/github/pcdshub/lcls-twincat-vacuum/jobs/590814009, for example:

```
Traceback (most recent call last):
  File "/home/travis/miniconda/lib/python3.9/site-packages/sphinx/config.py", line 350, in eval_config_file
    exec(code, namespace)
  File "/home/travis/docs/source/conf.py", line 18, in <module>
    import doctr_versions_menu
  File "/home/travis/miniconda/lib/python3.9/site-packages/doctr_versions_menu/__init__.py", line 14, in <module>
    from . import cli, ext
  File "/home/travis/miniconda/lib/python3.9/site-packages/doctr_versions_menu/cli.py", line 15, in <module>
    from .version_data import get_version_data
  File "/home/travis/miniconda/lib/python3.9/site-packages/doctr_versions_menu/version_data.py", line 10, in <module>
    from .groups import get_groups
  File "/home/travis/miniconda/lib/python3.9/site-packages/doctr_versions_menu/groups.py", line 2, in <module>
    from packaging.version import LegacyVersion
ImportError: cannot import name 'LegacyVersion' from 'packaging.version' (/home/travis/miniconda/lib/python3.9/site-packages/packaging/version.py)
```

### CODE REVIEW

**Comment by ZLLentz** [comment]
I'll make a dummy PR in some repo to test this

**Comment by klauer** [comment]
Closes #89

**Comment by ZLLentz** [comment]
This did let the build proceed as it did in previous weeks:
https://app.travis-ci.com/github/pcdshub/lcls-plc-kfe-motion/jobs/590818444

**Review by klauer — APPROVED** [review]
LGTM

Tweaked your comment to make it auto-close the issue

**Comment by ZLLentz** [comment]
You can also click on the right hand side under "development" and select an issue instead of modifying the description if the pr writer forgot

**Review by tangkong — APPROVED** [review]
LGTM

**Pull request merged**
